name: valorzhong_injector
version: 0.0.2
author: Valor Zhong <valorzhong@gmail.com>
description: A simple, easy and flexible dependency injection library, based on Dart
homepage: https://github.com/games/injector
documentation: https://github.com/games/injector

dev_dependencies:
  unittest: any

